Dev4
KoneeVibes/workplacepay pull request #31
Opened 2024-09-22 01:40 UTC by Newton-Ephraim

sorry i didn't deliver all these while, abeg no vex.

2024-09-22 01:41 UTC, Newton-Ephraim commented
check for any correction please

2024-09-22 23:33 UTC, KoneeVibes requested changes
This get started page is not responsive. It is also not a replica of the design. Please take some time to clean this up.

Here are some concerns:

![image](https://github.com/user-attachments/assets/2ed4f6ef-c8a0-4e2b-b109-8eff5e1fc678)
![image](https://github.com/user-attachments/assets/657c70eb-8487-4784-b4dc-d235b65e2b2b)

2024-09-22 23:33 UTC, KoneeVibes commented on src/assets/images/Rectangle 90.png
You should name this file rightly. The whitespace between "Rectangle" and "90" is causing the entire application to break on my end.

2024-09-22 23:35 UTC, KoneeVibes requested changes
Also, you have not completed this auth page. You see, considering that you have now used 4 weeks on this task, I would have expected that you just cleaned this up since Awele is not available.

2024-09-23 15:58 UTC, KoneeVibes approved these changes

2024-09-23 16:02 UTC, merged